### Pobierz wszystkie zadania
GET http://localhost:3000/tasks

### Dodaj nowe zadanie (pamiętaj o pustej linii po nagłówkach!)
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Nauczyć się NestJS i Angulara",
  "description": "Zrobić pełny projekt fullstack",
  "authorId": 1
}

### ZMIEN STATUS ZADANIA NA UKOŃCZONE
PATCH http://localhost:3000/tasks/38/status
Content-Type: application/json

{
  "isCompleted": true
}

### REJESTRACJA NOWEGO UŻYTKOWNIKA
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "pablo23k8@gmail.com",
  "password": "test1234"
}